config/routes.rb
OmniauthDemo::Application.routes.draw do

  Mercury::Engine.routes

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  devise_scope :user do
    get 'login', :to => 'devise/sessions#new', :as => :login
    get 'logout', :to => 'devise/sessions#destroy', :as => :logout
  end
  
  #constraints :subdomain => '' do
  #  match '/' => redirect('/') #("http://www.pcsenegal.com")
  #end
  
  resources :users, :only => [ :index, :show, :edit, :update, :destroy ] do
    collection do
      get :search
      get :table
    end
  end

  resources :documents, :path => 'files' do
    member do
      get :download
    end
    collection do
      get :search
      get :table
    end
  end

  resources :case_studies do
    collection do
      get :added
      get :updated
      get :search
      get :table
    end
    member do
      post :mercury_update
    end
  end

  resources :imports do
    member do
      get 'process_yaml'
    end
  end

  resources :languages

  resources :libraries do
    member do
      get :download
      get :podcast, :as => :podcast, :defaults => { :format => 'xml' }
    end
    collection do
      get :search
    end
  end

  resources :stacks, :only => [ :index, :new, :create, :destroy ]

  resources :photos do
    collection do
      get :search
    end
    member do
      get :embed
    end
  end

  resources :sites, :sectors, :positions, :jobs, :staff, :websites, :identities, :stages, :scopes, :regiontypes, :pc_regions, :regions, :volunteers, :moments

  resources :blogs do
    collection do
      get :updated
    end
  end

  resources :feedback, :except => [:edit, :update] do
    collection do
      get :volunteer_request
    end
  end

  resources :contributions, :only => [ :index, :new, :create, :destroy ]

  resources :permissions, :only => [ :index, :new, :create, :destroy ]

  resources :pages do
    collection do
      get :updated
      get :added
      get :popular
      get :ajax
      get :search
      get :feed, :as => :feed, :defaults => { :format => 'atom' }
      get :table
    end
    member do
      post :mercury_update
    end
  end

  match '/disclaimer', :to => 'statics#disclaimer'
  match '/privacy', :to => 'statics#privacy'
  match '/security', :to => 'statics#security'
  match '/about_us', :to => 'statics#about_us'
  match '/splash', :to => 'statics#splash'
  match '/help', :to => 'statics#help'
  match '/search', :to => 'statics#search'
  match '/welcome', :to => 'statics#welcome', :as => :entry
  match '/goodbye', :to => 'statics#goodbye', :as => :exit
  match '/dashboard', :to => 'statics#dashboard', :as => :dashboard
  match '/timeline', :to => 'statics#timeline', :as => :timeline

  match '/feedback', :to => 'feedback#new'
  match '/feed/pages', :to => 'pages#updated'
  
  match '/facebook' => redirect('https://apps.facebook.com/peacecorps')
  match '/youtube' => redirect('https://www.youtube.com/pcsenegaladmin')
  match '/twitter' => redirect('http://twitter.com/#!/pc_senegal')
    
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'statics#splash'

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/library.rb
class Library < ActiveRecord::Base
  
  require 'zip/zip'
  require 'zip/zipfilesystem'

  acts_as_taggable_on :tags
  
  # records of stackable objects linked against this library
  has_many :stacks, :dependent => :destroy

  # legacy
  # has_many :documents, :through => :stacks, :class_name => 'Document'
  # has_many :photos, :through => :stacks, :class_name => 'Photo'

  # user who owns/manages this library
  belongs_to :user

  validates :name, :user_id, :country, :presence => true

  def self.available(item, user = nil)
    # no libraries, no user
    if item.libraries.empty? && user.nil?
      Library.all
    # libraries, no user
    elsif !item.libraries.empty? && user.nil?
      libraries = []
      return_libraries = []
      item.libraries.each do |lib|
        libraries << lib
      end
      Library.all.each do |lib|
        return_libraries << lib unless libraries.include?(lib)
      end
      return_libraries
    # no libraries, user
    elsif item.libraries.empty? && !user.nil?
      user.libraries.all
    # libraries, user
    else
      libraries = []
      return_libraries = []
      item.libraries.each do |lib|
        libraries << lib
      end
      Library.where("user_id = ?", user.id).each do |lib|
        return_libraries << lib unless libraries.include?(lib)
      end
      return_libraries
    end
  end

  # retrieves the actual document objects from the stacks
  def documents
    documents = []
    stacks.documents.all.each do |stack|
      documents << stack.stackable
    end
    documents
  end

  # retrieves the actual photo objects from the stacks
  def photos
    photos = []
    stacks.photos.all.each do |stack|
      photos << stack.stackable
    end
    photos
  end

  def mp3s
    mp3s = []
    stacks.documents.all.each do |stack|
      mp3s << stack.stackable unless stack.stackable.audio_length.nil?
    end
    mp3s
  end

  # sets the url to include the title
  def to_param
    "#{id}-#{canonical_title.parameterize}"
  end

  # standard title attribute, for standardization
  def canonical_title
    name
  end
  
  # all objects in the library
  def contents
    documents + photos
  end
  
  # file name for downloading compressed library, including extension
  def file_name
    "#{self.full_name}.zip"
  end
  
  # full name of the archive, for use as folder name
  def full_name
    "#{self.name}-all_files"
  end
  
  # package library into .zip file for bulk download
  # this should probably be a worker task, but oh well...
  #
  # @todo make sure that only documents authorized for viewing are included.
  def bundle

    # set the path.
    # on heroku, this amounts to a temporary path
    # so i've not included any system for removing them
    # except recreating them
    # put it in the appropriate folder for the environment
    bundle_filename = "public/system/#{Rails.env}/#{file_name}"

    # check to see if the file exists already, and if it does, delete it.
    if File.file?(bundle_filename)
      File.delete(bundle_filename)
    end

    # open or create the zip file
    Zip::ZipFile.open(bundle_filename, Zip::ZipFile::CREATE) {
      |zipfile|
      # collect the library's objects
      self.documents.collect {
        |document|
          # add each track to the archive, using its canonical_title for file name
          zipfile.add( "#{full_name}/files/#{document.canonical_title}", document.file.to_file)
      }
      self.photos.collect {
        |photo|
          # add each track to the archive, using its canonical_title and credit for file name
          zipfile.add( "#{full_name}/photos/#{photo.canonical_title}-#{photo.attribution ? photo.attribution : photo.user.name}", photo.photo.to_file)
      }
    }

    # set read permissions on the file
    File.chmod(0644, bundle_filename)

    # save the object
    self.save
  end

end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  
  load_and_authorize_resource
  
  # GET /libraries
  # GET /libraries.json
  def index
    if user_signed_in? && current_user.role?(:moderator)
      @libraries = Library.order('name ASC').paginate(:page => params[:page])
    else
      @libraries = @libraries.order('name ASC').paginate(:page => params[:page])
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @libraries }
    end
  end

  def search
    if params[:q]
      @libraries = Library.search(params[:q]).paginate(:page => params[:page], :per_page => 20)
      render 'index'
    else
      redirect_to libraries_path
    end
  end

  # GET /libraries/1
  # GET /libraries/1.json
  def show
    @library = Library.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @library }
    end
  end

  # GET /libraries/new
  # GET /libraries/new.json
  def new
    @library = Library.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @library }
    end
  end

  # GET /libraries/1/edit
  def edit
    @library = Library.find(params[:id])
  end

  # POST /libraries
  # POST /libraries.json
  def create
    @library = Library.new(params[:library])

    respond_to do |format|
      if @library.save
        format.html { redirect_to @library, notice: 'Library was successfully created.' }
        format.json { render json: @library, status: :created, location: @library }
      else
        format.html { render action: "new" }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /libraries/1
  # PUT /libraries/1.json
  def update
    @library = Library.find(params[:id])

    respond_to do |format|
      if @library.update_attributes(params[:library])
        format.html { redirect_to @library, notice: 'Library was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1
  # DELETE /libraries/1.json
  def destroy
    @library = Library.find(params[:id])
    @library.destroy

    respond_to do |format|
      format.html { redirect_to libraries_url }
      format.json { head :ok }
    end
  end
  
  # GET /libraries/1/download
  def download
    @library = Library.find(params[:id])
    
    if @library.bundle
      send_file "public/system/#{Rails.env}/#{@library.file_name}"
      File.delete("public/system/#{Rails.env}/#{@library.file_name}")
    else
      redirect_to @library, notice: 'There was an error zipping your file. Please try again later.'
    end
  end
  
  # GET /libraries/1/podcast
  def podcast
    @library = Library.find(params[:id])
    @title = @library.name
    @link = podcast_library_url(@library)
    @language = 'en-us'
    @copyright = '2010 - 2012, Peace Corps ' + @library.country
    @subtitle = "Peace Corps #{@library.country} | #{@library.name}"
    @author = "Peace Corps #{@library.country}"
    @description = @library.description
    @itunes_name = 'Peace Corps Senegal'
    @itunes_email = 'admin@pcsenegal.org'

    # the mp3 files
    @mp3s = @library.mp3s
      
    if @mp3s.empty?
      redirect_to @library, notice: 'There is currently no podcast associated with this library.'
    else
      respond_to do |format|
        format.xml { render :layout => false }
      end
    end
  end
  
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.haml
= form_for(@library) do |f|
  = render 'shared/form_error' if @library.errors.any?

  .field
    = f.label :name, 'Name*'
    = f.text_field :name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :country_id, 'Country*'
    = f.country_select(:country, 'SN')
  - if can? :manage, Library
    .field
      = f.label :user_id, 'User*'
      = f.collection_select(:user_id, User.all, :id, :name)
  - else
    = f.hidden_field(:user_id, :value => current_user.id)
  = render 'shared/tag_field', :f => f
  .actions
    = f.submit

app/views/libraries/_library.html.haml
.feed_item
  .floatleft= link_to image_tag((library.photos.any? ? library.photos.first.photo.url(:icon) : 'blank.png'), :width => '80'), library, :class => 'avatar'
  %h3
    = flag_icon(library.country.downcase)
    = link_to library.name, library
    %small
      = pluralize(library.stacks.count, 'item')
  %p
    = library.description
    = render 'shared/tags', :tags => library.tag_list
    %br
    maintained by
    = link_to library.user.name, library.user
  %hr.clearfloat

app/views/libraries/_menu.html.haml
.subnav
  %ul.nav.nav-pills
    %li.dropdown
      %a.dropdown-toggle{'data-toggle' => 'dropdown', 'href' => '#'}
        Sort by
        %b.caret
      %ul.dropdown-menu
        %li= link_to 'Alphabetical', libraries_path
        %li= link_to 'Recently updated', libraries_path
        %li= link_to 'Recently added', libraries_path
    %li= link_to 'Table View', libraries_path
    %li= link_to 'Create Library', new_library_path if can? :create, Library
    %li= link_to 'Podcast it!', podcast_library_path, :rel => 'popover-bottom', :title => 'What does this do?', 'data-content' => "Clicking this link will take you to an RSS Podcast feed for all audio files in this library. Copy this link address, open iTunes, and past the URL into <code>Advanced -> Subscribe to Podcast</code>. It's that easy! You can also submit this URL to the iTunes store to create a registered podcast." if @library
    %li.dropdown
      %a.dropdown-toggle{'data-toggle' => 'dropdown', 'href' => '#'}
        Actions
        %b.caret
      %ul.dropdown-menu
        %li= link_to 'Download as .zip', download_library_path(@library)
        %li= link_to 'Edit', edit_library_path(@library) if can? :edit, @library
        %li= link_to 'Destroy', '' if can? :destroy, @library
    = render 'shared/search'

app/views/libraries/edit.html.haml
.row
  .span-5
    = render 'shared/menu'
  .span-15
    = render 'form'
  .span-4.last

app/views/libraries/index.html.haml
.container
  .row
    .span3
      = render 'shared/menu'
    .span7
      = render 'menu'
      = render @libraries
      .center= will_paginate
    .span2

app/views/libraries/new.html.haml
.container
  .row
    .span3
      = render 'shared/menu'
    .span7
      %h1 Create a library
      = render 'form'
    .span2

app/views/libraries/podcast.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">
	<channel>
		<%= render 'shared/podcast' %>
		<% @mp3s.each do |mp3| %>
			<item>
				<title><%= mp3.name %></title>
				<itunes:author><%= mp3.author ? mp3.author : "Peace Corps #{mp3.user.country}" %></itunes:author>
				<itunes:subtitle><%= mp3.description %></itunes:subtitle>
				<itunes:summary><%= mp3.description %></itunes:summary>
				<enclosure url="<%= mp3.file.url %>" length="<%= mp3.file.size %>" type="<%= mp3.file_content_type %>" />
				<guid><%= mp3.file.url %></guid>
				<pubDate><%= mp3.updated_at.strftime('%a, %d %b %Y %H:%M:%S %z') %></pubDate>
        <itunes:duration><%= mp3.formatted_audio_length %></itunes:duration>
				<itunes:keywords><%= mp3.tag_list %></itunes:keywords>
			</item>
		<% end %>
	</channel>
</rss>

app/views/libraries/show.html.haml
.row
  .span3
    = render 'shared/menu'
  .span9
    = render 'menu'
    .row
      .span5
        %h1
          = flag_icon(@library.country.downcase)
          = @library.name
          %small
            = link_to '#bitly_url_qrcode', 'data-toggle' => 'modal' do
              %i.icon-qrcode{ :rel => 'popover-top', :title => 'Get a QR Code', 'data-content' => "<h3>What's a QR Code?</h3>QR Codes are 3-dimensional barcodes which can be scanned by smartphones and used to store URLs. This link will take you to a QR Code image you can use online or in print to represent this library." }
            = link_to '#bitly_url', 'data-toggle' => 'modal' do
              %i.icon-resize-small{ :rel => 'popover-top', :title => 'Get a shortened URL', 'data-content' => "<h3>Why should I care?</h3>URLs can be long. Just take a look up in your address bar. If you want to Tweet this URL, post it somewhere, or just save space, you can use this one instead. Click to retrieve it." }
        %h4= @library.description
      .span4
        %h3
          Questions? Comments? This library is managed by
        %ul.feed
          = render @library.user
    .tabbable
      %ul.nav.nav-tabs
        %li.active= link_to 'Files', '#files', 'data-toggle' => 'tab'
        %li= link_to 'Photos', '#photos', 'data-toggle' => 'tab'
      .tab-content
        .tab-pane#files.active
          = render @library.documents
        .tab-pane#photos
          = render @library.photos
= render 'shared/modal_standard',:id => "bitly_url", :title => 'Bit.ly Shortened URL', :body => raw("<p>#{shorten_url(library_url(@library))}<p>#{link_to 'Why is this not a link?', '/help#shortlinks'}</p>"), :footer => nil
= render 'shared/modal_standard',:id => "bitly_url_qrcode", :title => 'QR Code', :body => image_tag(shorten_url(library_url(@library), :qr, :medium => 'qrcode')) + raw("<p>#{link_to 'What do I do with this?', '/help#qrcodes'}</p>"), :footer => nil
 